APP_MAP = {
    "chrome": "start chrome",
    "google chrome": "start chrome",
    "notepad": "start notepad",
    "calculator": "start calc",
    "paint": "start mspaint",
    "cmd": "start cmd",
    "command prompt": "start cmd",
    "powershell": "start powershell",
    "task manager": "start taskmgr",
    "explorer": "start explorer",
    "file explorer": "start explorer",
    "settings": "start ms-settings:",
    "control panel": "start control",
    "word": "start winword",
    "excel": "start excel",
    "vscode": "start code",
    "vs code": "start code",
    "youtube": "start https://www.youtube.com",
    "gmail": "start https://mail.google.com",
    "google": "start https://www.google.com",
}